#pragma once
#define MOTOR_J0_PWM GPIO_NUM_3
#define MOTOR_J0_DIR GPIO_NUM_2

#define MOTOR_J1_PWM_H GPIO_NUM_4
#define MOTOR_J1_DIR_L GPIO_NUM_5

#define MOTOR_J2_PWM_H GPIO_NUM_6
#define MOTOR_J2_PWM_L GPIO_NUM_7

#define MOTOR_J3_PWM_H GPIO_NUM_8
#define MOTOR_J3_PWM_L GPIO_NUM_9

#define MOTOR_J4_PWM_H GPIO_NUM_14
#define MOTOR_J4_PWM_L GPIO_NUM_15
